import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Recipe App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/iconfav.png'/>
      </head>
      <body className={inter.className}>
        
        <Navbar />
        {children}
      </body>
    </html>
  )
}
